#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""套件自检：**现场造一份小课件 PDF**，把整套流水线从零跑一遍。

用法：
    python selftest.py [--keep] [--dir 输出目录]

为什么要它：套件号称「自包含、换个课件也能跑」，那就得有一条**不依赖任何已有项目**
的证据链。这里用 PyMuPDF 现造一份 6 页的小 PDF（不需要联网、不需要外部素材），
然后调用 run_all.py 走完 建骨架 → 渲染 → 构建 → 四项体检 → 截图，
最后按输出里的关键词判定 PASS/FAIL。

预期：机械部分全绿；「待补页面 6/6」是**正常**的 —— 讲解内容本来就是留给人/agent 写的。

输出：**实时透传**子进程日志（不再跑完才打印，避免「看着像卡死」）。
若某一步超过 120 秒没有新输出会点名警告，超过 900 秒直接终止并报出卡在哪一步。
"""
import argparse
import ctypes
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import time

HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.dirname(HERE)

sys.path.insert(0, HERE)
import kitpath  # noqa: E402

kitpath.require_deps('pymupdf')   # 缺包时给出 pip 命令，而不是 ModuleNotFoundError

import pymupdf  # noqa: E402

# 整条流水线约 1~2 分钟。以前这里是 capture_output=True + 跑完一次性打印，
# 期间**一个字都不输出，看上去完全像卡死**（用户就是这么反馈的），
# 而且真卡住时也看不出卡在哪一步。现在改成实时透传 + 两级看门狗。
STALL_WARN = 120     # 秒：超过这么久没有任何新输出 → 警告并点名当前步骤
HARD_LIMIT = 900     # 秒：整体硬超时 → kill 并说明停在哪一步


def long_path(p):
    """展开 8.3 短路径。tempfile.gettempdir() 在本机返回 SHENYU~1，
    Chromium 在短路径下会静默失败（见 references/pitfalls.md 第 18 条）。"""
    if os.name != 'nt':
        return p
    try:
        buf = ctypes.create_unicode_buffer(32768)
        n = ctypes.windll.kernel32.GetLongPathNameW(str(p), buf, 32768)
        if 0 < n < 32768:
            return buf.value
    except Exception:  # noqa: BLE001
        pass
    return p

PAGES = [
    ('Selftest Courseware', 'A tiny deck generated by selftest.py', [
        'This PDF exists only to prove the kit can run end to end.',
        'No network, no external assets, six pages.']),
    ('1  Overview', 'What this deck is about', [
        'Section A talks about counting things.',
        'Section B talks about smoothing the counts.',
        'Section C wraps up.']),
    ('2  Counting', 'The first idea', [
        'Count how often each outcome appears, then divide by N.',
        'p(x) = count(x) / N  -- the whole idea fits on one line.',
        'Watch out: a value that never appears gets probability zero.']),
    ('3  Smoothing', 'Fixing the zero', [
        'Add a small constant to every count: (count + a) / (N + k*a).',
        'This is Laplace smoothing; the deck uses it later.',
        'Note the trade-off: bigger a means less confident predictions.']),
    ('4  Summary', 'Putting it together', [
        'Counting plus smoothing gives a usable classifier.',
        'Next deck: how to pick the smoothing constant.']),
    ('5  Appendix', 'Exercise sheet', [
        'Exercise 1: estimate p from a small sample.',
        'Exercise 2: compare two smoothing constants.']),
]


def synth(path):
    doc = pymupdf.open()
    for i, (title, sub, lines) in enumerate(PAGES, 1):
        page = doc.new_page(width=595, height=842)
        page.insert_text((64, 90), title, fontsize=22)
        page.insert_text((64, 124), sub, fontsize=12)
        y = 170
        for ln in lines:
            page.insert_text((64, y), ln, fontsize=11)
            y += 22
        page.insert_text((500, 800), 'P%d' % i, fontsize=10)
    doc.save(path)
    doc.close()
    return path


def run_pipeline(cmd):
    """实时透传子进程输出，并在「长时间没有新输出」时点名当前步骤。

    返回值 (全部输出文本, 退出码)。超时被 kill 时退出码为 None。
    """
    buf = []
    lock = threading.Lock()
    state = {'last': time.time(), 'step': '(启动中)', 'done': False}

    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, encoding='utf-8', errors='replace', bufsize=1,
    )

    def reader():
        try:
            for line in proc.stdout:
                with lock:
                    buf.append(line)
                    state['last'] = time.time()
                    m = re.search(r'▶\s*(.+?)\s*$', line.rstrip())
                    if m:
                        state['step'] = m.group(1)
                sys.stdout.write(line)
                sys.stdout.flush()
        finally:
            with lock:
                state['done'] = True

    th = threading.Thread(target=reader, daemon=True)
    th.start()

    t0 = time.time()
    warned = set()
    while True:
        with lock:
            done, idle, step = state['done'], time.time() - state['last'], state['step']
        if done and proc.poll() is not None:
            break
        if idle > STALL_WARN and step not in warned:
            warned.add(step)
            print('\n⚠ 已 %d 秒没有新输出 —— 当前停在：%s\n'
                  '  （真卡住的话多半是这一步的浏览器/探针没退，'
                  '见 references/pitfalls.md 第 18、21 条）\n' % (int(idle), step), flush=True)
        if time.time() - t0 > HARD_LIMIT:
            proc.kill()
            print('\n✘ 流水线超过 %d 秒仍未结束，已终止。最后停在：%s\n' % (HARD_LIMIT, step),
                  flush=True)
            break
        time.sleep(1)
    th.join(timeout=5)
    return ''.join(buf), proc.poll()


def semantic_path(base, pdf):
    """语义路线：--stage plan → 校对 outline → 改写确认 → --outline 建骨架 → build → 三校验。

    这是「先定结构、再写内容」路线的自测，与上面机械路线互补。synth 造的英文 PDF
    没有书签/编号信号，plan_outline 会退化为 fallback（每 8 页一段），这里照单全收
    再程序化把它改成「两段语义结构」——这一步模拟的正是 agent 填语义 + 用户确认。
    """
    sem = os.path.join(base, 'semantic')
    os.makedirs(sem, exist_ok=True)
    checks = []
    outline_path = os.path.join(sem, '_plan', 'outline.json')

    # ① --stage plan：只渲染逐页图 + 出 outline 草案，不建骨架、不构建
    out, rc = run_pipeline([sys.executable, '-u', os.path.join(HERE, 'run_all.py'),
                            pdf, '--out', sem, '--stage', 'plan'])
    checks.append(('① --stage plan 退出码 0', rc == 0))
    checks.append(('① 产出 outline 草案', os.path.exists(outline_path)))

    # ② 校对 outline：结构、覆盖性、封面字段、草案状态
    d = None
    if os.path.exists(outline_path):
        d = json.load(open(outline_path, encoding='utf-8'))
        secs = d.get('sections') or []
        seen = [n for s in secs for n in (s.get('pages') or [])]
        checks.append(('② outline.schema=v1', d.get('schema') == 'outline/v1'))
        checks.append(('② sections 非空', len(secs) >= 1))
        checks.append(('② 页码覆盖 2..N 且不重复',
                       sorted(seen) == list(range(2, len(PAGES) + 1))))
        checks.append(('② cover 字段存在', isinstance(d.get('cover'), dict)))
        checks.append(('② 草案未确认（confirmed=false）', d.get('confirmed') is False))

    # ③ 程序化改写为「确认过的两段语义结构」，模拟 agent 填语义 + 用户确认
    if d is not None:
        d['source'] = 'semantic'
        d['sections'] = [
            {'key': 's1', 'name': 'Counting', 'pages': [2, 3], 'origin': 'semantic',
             'part_index': 1, 'toc_label': '1 · Counting（P2–P3）'},
            {'key': 's2', 'name': 'Smoothing and wrap-up', 'pages': [4, 5, 6],
             'origin': 'semantic', 'part_index': 2,
             'toc_label': '2 · Smoothing and wrap-up（P4–P6）'},
        ]
        d['confirmed'] = True
        d['confirmed_by'] = 'selftest'
        open(outline_path, 'w', encoding='utf-8').write(
            json.dumps(d, ensure_ascii=False, indent=2) + '\n')
    checks.append(('③ 改写 outline 为两段语义结构',
                   d is not None and len(d.get('sections') or []) == 2))

    # ④ --outline 建骨架 → build → 三校验（run_all --skip-init）
    if d is not None:
        _, rc2 = run_pipeline([sys.executable, '-u', os.path.join(HERE, 'init_project.py'),
                               pdf, '--out', sem, '--outline', outline_path])
        checks.append(('④ init --outline 建骨架退出码 0', rc2 == 0))
        out3, rc3 = run_pipeline([sys.executable, '-u', os.path.join(HERE, 'run_all.py'),
                                  pdf, '--out', sem, '--skip-init'])
        checks.append(('④ build + 体检退出码 0', rc3 == 0))
        cfg_path = os.path.join(sem, 'config.json')
        if os.path.exists(cfg_path):
            cfg = json.load(open(cfg_path, encoding='utf-8'))
            checks.append(('④ config.outline.confirmed=true',
                           bool((cfg.get('outline') or {}).get('confirmed'))))
            seg_names = [g[0] for g in (cfg.get('groups') or [])]
            checks.append(('④ 目录按语义切成 2 段',
                           any(x.startswith('1 ·') for x in seg_names)
                           and any(x.startswith('2 ·') for x in seg_names)))
        checks.append(('④ 产物已生成', any(f.endswith('-逐页精解.html') for f in os.listdir(sem))))
        checks.append(('④ check_ui ALL PASS', re.search(r'ALL PASS', out3) is not None))
        checks.append(('④ probe_marks PASS', re.search(r'RESULT: PASS', out3) is not None))
        checks.append(('④ probe_doc 报进度', re.search(r'内容进度', out3) is not None))
        checks.append(('④ run_all 判定全绿', re.search(r'机械部分全绿', out3) is not None))
    return checks


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--keep', action='store_true', help='保留生成的项目目录')
    ap.add_argument('--dir', default=None, help='指定项目目录（默认系统临时目录）')
    a = ap.parse_args()

    base = long_path(a.dir or os.path.join(tempfile.gettempdir(), 'slides-kit-selftest'))
    if os.path.exists(base) and not a.keep:
        shutil.rmtree(base, ignore_errors=True)
    os.makedirs(base, exist_ok=True)
    pdf = os.path.join(base, 'selftest-deck.pdf')
    if not os.path.exists(pdf):
        synth(pdf)
    print('测试课件: %s (%.1f KB)' % (pdf, os.path.getsize(pdf) / 1024))

    # -u：让 run_all 的输出不缓冲，实时看得到进度
    cmd = [sys.executable, '-u', os.path.join(HERE, 'run_all.py'), pdf, '--out', base, '--force']
    print('开始跑流水线（实时输出如下，约 1~2 分钟）：\n', flush=True)
    t0 = time.time()
    out, rc = run_pipeline(cmd)
    print('\n流水线耗时 %.1f 秒，退出码 %s' % (time.time() - t0, rc))

    def has(pat):
        return re.search(pat, out) is not None

    checks = [
        ('骨架生成', os.path.exists(os.path.join(base, 'config.json'))),
        ('内容分片生成', len([f for f in os.listdir(os.path.join(base, 'content'))
                             if f.endswith('.html')]) >= 4),
        ('离线 KaTeX 就位', os.path.exists(os.path.join(base, '_katex', 'katex.offline.css'))),
        ('缩略图齐全', len([f for f in os.listdir(os.path.join(base, '_extract'))
                            if f.startswith('thumb_')]) == len(PAGES)),
        ('逐页大图齐全', len([f for f in os.listdir(os.path.join(base, '_extract'))
                              if f.startswith('page-')]) == len(PAGES)),
        ('产物已生成', any(f.endswith('-逐页精解.html') for f in os.listdir(base))),
        ('check_ui ALL PASS', has(r'ALL PASS')),
        ('probe_marks PASS', has(r'RESULT: PASS')),
        ('probe_doc 报出了进度', has(r'内容进度')),
        ('run_all 判定全绿', has(r'机械部分全绿')),
    ]

    # 语义路线：与上面的机械路线互补，两条都要能在本脚本里跑通
    print('\n' + '=' * 72)
    print('开始跑语义路线（--stage plan → 校对 outline → --outline → build → 三校验）：\n',
          flush=True)
    checks.extend(semantic_path(base, pdf))

    print('=' * 72)
    bad = 0
    for name, ok in checks:
        print('  %s %s' % ('✔' if ok else '✘', name))
        bad += 0 if ok else 1
    print('=' * 72)
    print('自检结果: %s' % ('PASS' if not bad else 'FAIL（%d 项不通过）' % bad))
    if a.keep:
        print('保留目录: %s' % base)
    sys.exit(0 if not bad else 1)


if __name__ == '__main__':
    main()
